#!/usr/bin/env bash
set -euo pipefail

# ───────────────────────────────────────────────────────
# podman-lab — Automated Deployment Script
# ───────────────────────────────────────────────────────
# Usage: ./setup.sh [--domain runemal.cloud]
#
# Placeholders replaced in quadlet files:
#   __USER__        → $USER
#   __UID__         → $(id -u)
#   __DOMAIN__      → $DOMAIN (default runemal.cloud)
#   __POSTGRES_IP__ → $POSTGRES_IP (default 10.89.1.2)
#   __REDIS_IP__    → $REDIS_IP    (default 10.89.1.3)
#   __GITEA_IP__    → $GITEA_IP    (default 10.89.1.4)
#   __WOODPECKER_IP__ → $WOODPECKER_IP (default 10.89.1.5)
#
# Also generates random secrets, copies everything
# into place, and reloads systemd.
# ───────────────────────────────────────────────────────

DOMAIN="${DOMAIN:-runemal.cloud}"

# ── Container IPs ──────────────────────────────────
# podman 4.9 (CNI backend) lacks container DNS, so
# each service gets a fixed IP and dependent containers
# inject /etc/hosts entries via --add-host (PodmanArgs).
# Override via env vars or --network-subnet flag:
#   NETWORK_SUBNET=10.89.1 POSTGRES_IP=10.89.1.10 ./setup.sh
NETWORK_SUBNET="${NETWORK_SUBNET:-10.89.1}"
POSTGRES_IP="${POSTGRES_IP:-${NETWORK_SUBNET}.2}"
REDIS_IP="${REDIS_IP:-${NETWORK_SUBNET}.3}"
GITEA_IP="${GITEA_IP:-${NETWORK_SUBNET}.4}"
WOODPECKER_IP="${WOODPECKER_IP:-${NETWORK_SUBNET}.5}"

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
QUADLET_SRC="$REPO_DIR/quadlets"
SYSTEMD_SRC="$REPO_DIR/systemd"
CONFIG_SRC="$REPO_DIR/config"

CONTAINERS_DIR="$HOME/.config/containers/systemd"
USER_SYSTEMD_DIR="$HOME/.config/systemd/user"
DATA_DIR="$HOME/.local/share/podman-lab"
SECRETS_FILE="$DATA_DIR/secrets.env"

echo "=========================================="
echo "  podman-lab Setup"
echo "=========================================="
echo "Domain:      $DOMAIN"
echo "User:        $USER"
echo "UID:         $(id -u)"
echo "Subnet:      ${NETWORK_SUBNET}.0/24"
echo "IPs:         postgres=$POSTGRES_IP  redis=$REDIS_IP  gitea=$GITEA_IP  woodpecker=$WOODPECKER_IP"
echo "Repo:        $REPO_DIR"
echo "Quadlets ->  $CONTAINERS_DIR"
echo "Data    ->   $DATA_DIR"
echo "=========================================="

# ── Prerequisites ────────────────────────────────

command -v podman >/dev/null 2>&1 || { echo "ERROR: podman not found"; exit 1; }

if ! systemctl --user status >/dev/null 2>&1; then
  echo "ERROR: systemd --user not available"
  exit 1
fi

if ! loginctl show-user "$USER" 2>/dev/null | grep -q 'Linger=yes'; then
  echo "Enabling linger for $USER ..."
  loginctl enable-linger "$USER"
fi

# ── Create directory tree ────────────────────────

mkdir -p "$DATA_DIR"/{postgres/init.d,gitea,woodpecker,registry,minio,redis,backups,caddy}
mkdir -p "$CONTAINERS_DIR"
mkdir -p "$USER_SYSTEMD_DIR"

# ── Generate secrets ─────────────────────────────

echo "Generating random secrets ..."

POSTGRES_PASSWORD=$(openssl rand -hex 32)
GITEA_DB_PASS=$(openssl rand -hex 32)
WOODPECKER_DB_PASS=$(openssl rand -hex 32)
GITEA_SECRET_KEY=$(openssl rand -hex 32)
GITEA_INTERNAL_TOKEN=$(openssl rand -hex 32)
GITEA_LFS_JWT_SECRET=$(openssl rand -hex 32)
WOODPECKER_AGENT_SECRET=$(openssl rand -hex 32)
MINIO_ROOT_PASSWORD=$(openssl rand -hex 16)

cat > "$SECRETS_FILE" <<SECEOF
# podman-lab secrets — generated $(date)
# This file is sourced by quadlet containers via EnvironmentFile.
# Protect it: chmod 600

# --- PostgreSQL ---
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# --- Gitea ---
GITEA__database__PASSWD=$GITEA_DB_PASS
GITEA__server__SECRET_KEY=$GITEA_SECRET_KEY
GITEA__server__INTERNAL_TOKEN=$GITEA_INTERNAL_TOKEN
GITEA__server__LFS_JWT_SECRET=$GITEA_LFS_JWT_SECRET

# --- Woodpecker ---
WOODPECKER_GITEA_CLIENT=
WOODPECKER_GITEA_SECRET=
WOODPECKER_AGENT_SECRET=$WOODPECKER_AGENT_SECRET
WOODPECKER_DATABASE_DRIVER=postgres
WOODPECKER_DATABASE_DATASOURCE=postgres://woodpecker:${WOODPECKER_DB_PASS}@postgres:5432/woodpecker?sslmode=disable

# --- MinIO ---
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
SECEOF

chmod 600 "$SECRETS_FILE"
echo "Secrets written to $SECRETS_FILE"

# ── Generate init.sql for PostgreSQL ──────────────

cat > "$DATA_DIR/postgres/init.d/init.sql" <<SQLEOF
-- Generated by setup.sh $(date)
CREATE USER gitea WITH PASSWORD '${GITEA_DB_PASS}';
CREATE DATABASE gitea OWNER gitea;
CREATE USER woodpecker WITH PASSWORD '${WOODPECKER_DB_PASS}';
CREATE DATABASE woodpecker OWNER woodpecker;
SQLEOF

cp "$CONFIG_SRC/postgres/init.sql" "$DATA_DIR/postgres/init.d/init.sql"

echo "PostgreSQL init script written"

# ── Copy & interpolate quadlet files ─────────────

REPLACE_USER="$USER"
REPLACE_UID="$(id -u)"
REPLACE_DOMAIN="$DOMAIN"

echo "Deploying quadlet files ..."

for src in "$QUADLET_SRC"/*.container "$QUADLET_SRC"/*.volume "$QUADLET_SRC"/*.network; do
  [ -f "$src" ] || continue
  filename=$(basename "$src")
  dest="$CONTAINERS_DIR/$filename"

  sed \
    -e "s/__USER__/$REPLACE_USER/g" \
    -e "s/__UID__/$REPLACE_UID/g" \
    -e "s/__DOMAIN__/$REPLACE_DOMAIN/g" \
    -e "s/__POSTGRES_IP__/$POSTGRES_IP/g" \
    -e "s/__REDIS_IP__/$REDIS_IP/g" \
    -e "s/__GITEA_IP__/$GITEA_IP/g" \
    -e "s/__WOODPECKER_IP__/$WOODPECKER_IP/g" \
    "$src" > "$dest"

  echo "  $filename -> $dest"
done

# ── Copy systemd timer ──────────────────────────

if [ -f "$SYSTEMD_SRC/lab-backup.timer" ]; then
  cp "$SYSTEMD_SRC/lab-backup.timer" "$USER_SYSTEMD_DIR/lab-backup.timer"
  echo "  lab-backup.timer -> $USER_SYSTEMD_DIR/"
fi

# ── Copy registry config ───────────────────────

if [ -f "$CONFIG_SRC/registry/config.yml" ]; then
  mkdir -p "$DATA_DIR/registry"
  cp "$CONFIG_SRC/registry/config.yml" "$DATA_DIR/registry/config.yml"
  echo "  registry/config.yml -> $DATA_DIR/registry/"
fi

# ── Reload systemd ──────────────────────────────

echo "Reloading systemd user daemon ..."
systemctl --user daemon-reload

# ── Summary ─────────────────────────────────────

echo ""
echo "=========================================="
echo "  Deployment Complete"
echo "=========================================="
echo ""
echo "Start services (in order):"
echo "  systemctl --user start postgres"
echo "  systemctl --user start redis"
echo "  systemctl --user start gitea"
echo "  systemctl --user start woodpecker-server"
echo "  systemctl --user start wp-agent-{python,node,go,rust,java}"
echo "  systemctl --user start registry"
echo "  systemctl --user start minio"
echo "  systemctl --user enable --now lab-backup.timer"
echo ""
echo "Enable on boot:"
echo "  systemctl --user enable --now postgres redis gitea"
echo "  systemctl --user enable --now woodpecker-server"
echo "  systemctl --user enable --now wp-agent-{python,node,go,rust,java}"
echo "  systemctl --user enable --now registry minio"
echo ""
echo "Post-setup manual steps:"
echo "  1. Visit https://git.${DOMAIN}  and create admin account"
echo "  2. Settings -> Applications -> OAuth2"
echo "     Create app 'Woodpecker CI' with redirect:"
echo "     https://ci.${DOMAIN}/authorize"
echo "  3. Edit $SECRETS_FILE:"
echo "     WOODPECKER_GITEA_CLIENT=<from OAuth>"
echo "     WOODPECKER_GITEA_SECRET=<from OAuth>"
echo "  4. systemctl --user restart woodpecker-server"
echo "  5. Add subdomains to Cloudflare tunnel:"
echo "     git.${DOMAIN}     -> localhost:3000"
echo "     ci.${DOMAIN}      -> localhost:8000"
echo "     registry.${DOMAIN} -> localhost:5000"
echo "     minio.${DOMAIN}   -> localhost:9001"
echo "  6. systemctl --user start lab-python (or other dev env)"
echo "     podman exec -it lab-python /bin/bash"
echo ""
echo "Dev containers mount $HOME/Projects/  to /workspace/"
echo "=========================================="
